/*
 * SEG7.c
 *
 *  Created on: Oct 6, 2021
 *      Author: win 10
 */
#include "main.h"
void _7SEG_N(int num){
	if ( num==0 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6,1 );
	}
	if ( num==1 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6, 1 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1|GPIO_PIN_2, 0 );
	}
	if ( num==2 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_6,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2|GPIO_PIN_5,1 );
	}
	if ( num==3 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_6,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4|GPIO_PIN_5,1 );
	}
	if ( num==4 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_5|GPIO_PIN_6,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_3|GPIO_PIN_4,1 );
	}
	if ( num==5 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_5|GPIO_PIN_6,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1|GPIO_PIN_4,1);
	}
	if ( num==6 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1,1 );
	}
	if ( num==7 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6,1 );
	}
	if ( num==8 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6,0 );
	}
	if ( num==9 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_5|GPIO_PIN_6,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4,1 );
	}
	if(num==-1){
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6,1 );
	}
}

void _7SEG_D(int num){
	if ( num==0 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_13,1 );
	}
	if ( num==1 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13, 1 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8|GPIO_PIN_9, 0 );
	}
	if ( num==2 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_13,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9|GPIO_PIN_12,1 );
	}
	if ( num==3 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_13,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11|GPIO_PIN_12,1 );
	}
	if ( num==4 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_12|GPIO_PIN_13,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_10|GPIO_PIN_11,1 );
	}
	if ( num==5 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_12|GPIO_PIN_13,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8|GPIO_PIN_11,1);
	}
	if ( num==6 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8,1 );
	}
	if ( num==7 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13,1 );
	}
	if ( num==8 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13,0 );
	}
	if ( num==9 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_12|GPIO_PIN_13,0 );
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11,1 );
	}
	if ( num==-1 ) {
		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13,1 );
	}
}
